### ISSUE TITLE
Light color

### ISSUE THREAD

**Issue by Bharadwajshivam28** [priyankarpal/ProjectsHut#217]
Hello @priyankarpal  as i have seen in the page that the pagination slider color is very light .like on the page we are that page number color should de little dark for clear visibility but here the light is not much clear visible..

Dropping the screenshot

![Screenshot from 2023-04-21 18-21-02](https://user-images.githubusercontent.com/108119109/233641415-e2650be6-c573-4f3e-bfd6-b298bbfa12c0.png)
![Screenshot from 2023-04-21 18-20-57](https://user-images.githubusercontent.com/108119109/233641407-35e8a4ec-93e9-4b05-b0fb-fd5ba816cbe7.png)

We can give it a dark color to the box for clear visibility

**Comment by priyankarpal** [comment]
ok add a dark color

**Comment by Bharadwajshivam28** [comment]
@priyankarpal can you help me like i am not able to find where is the pagination and its all css defined

**Comment by priyankarpal** [comment]
It's fixed by someone today morning. Please check one time & if there are anything an issue you can msg

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by Bharadwajshivam28** [comment]
no its not fixed 

![Screenshot from 2023-04-22 20-07-25](https://user-images.githubusercontent.com/108119109/233791090-0286c433-6904-44c7-93e1-e1e2325ccb63.png)

**Comment by priyankarpal** [comment]
> no its not fixed
> 
> ![Screenshot from 2023-04-22 20-07-25](https://user-images.githubusercontent.com/108119109/233791090-0286c433-6904-44c7-93e1-e1e2325ccb63.png)

ok ok, so which color should we add here?

**Comment by Bharadwajshivam28** [comment]
we should go with dark color... i will test some dark color and drop the ss

**Comment by Bharadwajshivam28** [comment]
but can you help me like i am not able to find where is the css or tailwind defined of this pagination

**Comment by priyankarpal** [comment]
> but can you help me like i am not able to find where is the css or tailwind defined of this pagination

ok I will send you

**Comment by Bharadwajshivam28** [comment]
ya please drop it

**Comment by priyankarpal** [comment]
in the projects page 
```
<div className=" py-5 flex gap-2 flex-wrap justify-center text-black ">
        <button type="button" className="bg-white px-3 py-1 hover:bg-slate-200 rounded-md " onClick={prevPage}>
          Prev
        </button>
        {paginatedArr.map((ele, ind) => {
          return (
            <button
              type="button"
              className={`bg-white px-3 py-1 hover:bg-slate-200 rounded-md ${page === ind ? "text-primary" : null}`}
              onClick={() => setPage(ind)}
              key={ind}
            >
              {ind + 1}
            </button>
          )
        })}
        <button type="button" className="bg-white px-3 py-1 rounded-md hover:bg-slate-200" onClick={nextPage}>
          Next
        </button>
      </div>
```

these code

**Comment by Bharadwajshivam28** [comment]
thanks i will drop some sample color which will be more dark and good

**Comment by Bharadwajshivam28** [comment]
I have made the changes and now it looks more good then the before one as it is also more clear

![Screenshot from 2023-04-23 00-44-11](https://user-images.githubusercontent.com/108119109/233802496-e4b7e408-34b1-438b-b33c-7555beb61c57.png)
![Screenshot from 2023-04-23 00-44-15](https://user-images.githubusercontent.com/108119109/233802498-70ca5dc1-0533-45e4-9490-da8e0f802e0c.png)

**Comment by Bharadwajshivam28** [comment]
and when we go on the numbers then the box appears its by hover effect

**Comment by Bharadwajshivam28** [comment]
@priyankarpal

**Comment by priyankarpal** [comment]
create a PR

**Comment by Bharadwajshivam28** [comment]
so when one hover there should be a circle instead of square

**Comment by Bharadwajshivam28** [comment]
> create a PR. I think the previous one was much better. One thing you can do that when a user hovers it make bg circle

this one is more good looking i think

**Comment by priyankarpal** [comment]
> so when one hover there should be a circle instead of square

yes

**Comment by Bharadwajshivam28** [comment]
okay

**Comment by priyankarpal** [comment]
I think now it's looking good.  so I'm closing this PR
